### ISSUE TITLE
How to add you library and use it ? )

### ISSUE THREAD

**Issue by fmorau** [tancred/tweetnacl-objc#1]
Could you please add a description to README.md how can I link my project with your library and use it :)

**Comment by fmorau** [comment]
@tancred I need your help, boss :)

**Comment by tancred** [comment]
(sorry for taking so long to answer)

As for now, just copy the files to your own project.

However, the code in this repos is very much work in progress. I recommend you use [libsodium](https://github.com/jedisct1/libsodium) instead, and one of the excellent Objective-C bindings that exist for that library.

**Comment by fmorau** [comment]
@tancred ten four, Chief! 
Will try to work with it :) 
Is it https://github.com/gabriel/NAChloride ?

**Comment by fmorau** [comment]
and this one https://github.com/Tabbedout/SodiumObjc I also found :)

**Comment by tancred** [comment]
Absolutely! Those are the ones listed in the section "bindings for other languages" in the libsodium docs.

**Comment by fmorau** [comment]
@tancred Thank you  🙏
